Added attendance introduction paragraph
burgess01/code-of-conduct pull request #11
Opened 2022-03-05 17:52 UTC by annaliese-stone

## Description

### Type of Change
Added Introductory paragraph. 

- [ ] Feature
- [ ] Bug fix
- [X ] Documentation

## Contributors

- @annaliese-stone 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-03-05 18:22 UTC, solisa986 requested changes
Great job on this @annaliese-stone! I have requested some minor changes below. If you have any disagreements on my suggestions, please feel free to respond to their designated comment. Thanks for your hard work!

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Attendance is an important part of the teamwork this class requires. This includes arriving for class on time and prepared for the day's activities. Students are responsible for completing any requir
there should be "being" in front of prepared in the second sentence.

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Attendance is an important part of the teamwork this class requires. This includes arriving for class on time and prepared for the day's activities. Students are responsible for completing any requir
The second sentence starts off with 'this includes' and lists 2 examples of adhering to proper attendance. You might want to add in "this is including, but not limited to, ..." so that it fits the format of the rest of the sentence and so that proper attendance is not limited to just those 2 specifications.

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Attendance is an important part of the teamwork this class requires. This includes arriving for class on time and prepared for the day's activities. Students are responsible for completing any requir
Maybe you could include the expectation for responsibilities instead of what students should do. Acceptable/Unacceptable behavior will be outlined in the next two sections, so this paragraph should give more of an explanation of what exactly responsibility is. Ergo, "responsibility means being prepared by the start of class by doing 'x, y, z'."

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Similar to meeting attendance requirements,  meeting deadlines is extremely important. Ensuring work is done on time, if not earlier, is vital to staying on track for the semester and keeping your gr
Each section of the code of conduct should be separate -- it should not refer to previous sections. Maybe try rephrasing the first sentence to be "Complying with deadline requirements should be considered an important priority for students."

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Similar to meeting attendance requirements,  meeting deadlines is extremely important. Ensuring work is done on time, if not earlier, is vital to staying on track for the semester and keeping your gr
Maybe try providing a sentence explaining what the difference between group deadlines and student deadlines will entail -- this distinction is important if you will be including both terms.

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Similar to meeting attendance requirements,  meeting deadlines is extremely important. Ensuring work is done on time, if not earlier, is vital to staying on track for the semester and keeping your gr
there needs to be a "their" in front of "deadlines" in the third sentence.

2022-03-05 18:22 UTC, solisa986 commented on conduct.md
> +Similar to meeting attendance requirements,  meeting deadlines is extremely important. Ensuring work is done on time, if not earlier, is vital to staying on track for the semester and keeping your gr
Extensions primarily should only be granted if there are unforeseen circumstances preventing a student/group from completing their assignment. If you want to add a section about potential conflicts, then make sure that you specify the standard for exceptions first. Then clarify that an extension for potential conflicts (either technical or professional) "will be reviewed on a case by case basis".

2022-03-05 18:42 UTC, annaliese-stone commented on conduct.md
> +Attendance is an important part of the teamwork this class requires. This includes arriving for class on time and prepared for the day's activities. Students are responsible for completing any requir
Thank you! I just adjusted the attendance paragraph to better fit your suggestion.

2022-03-05 18:52 UTC, annaliese-stone commented on conduct.md
> +Similar to meeting attendance requirements,  meeting deadlines is extremely important. Ensuring work is done on time, if not earlier, is vital to staying on track for the semester and keeping your gr
Thank you! Just updated it with suggestions now.

2022-03-06 20:26 UTC, laurennevill approved these changes
looks good

2022-03-06 21:55 UTC, burgess01 submitted a review, later dismissed
I think this is really good!

2022-03-07 15:46 UTC, tuduun approved these changes
Looks good!

2022-03-07 15:50 UTC, annaliese-stone reviewed
Changes made! Thank you!

2022-03-07 18:44 UTC, solisa986 requested changes
Thank you for the changes @annaliese-stone! There are just two minor changes that need to be addressed before merging. Please let me know if you have any questions/if you feel these changes do not need to be implemented.

2022-03-07 18:44 UTC, solisa986 commented on conduct.md
> +Attendance is an important part of the teamwork this class requires. Students are responsible for ensuring they arrive to class on time and prepared for the day's activities. Students are also respon
You will have more clarity for the last sentence if you structured it like a list. Ergo, "...staying on track in regard to assignments, communicating with the professor early, and any potential absences." Of course, you may reformat this sentence to fit your sentence style if you prefer.

2022-03-07 18:44 UTC, solisa986 commented on conduct.md
> +Similar to meeting attendance requirements,  meeting deadlines is extremely important. Ensuring work is done on time, if not earlier, is vital to staying on track for the semester and keeping your gr
Please remove the reference to the attendance requirement, as this paragraph should be a standalone explanation of deadlines.

2022-03-07 20:53 UTC, solisa986 approved these changes
looks good!

2022-03-07 20:54 UTC, laurennevill approved these changes
I think these intro paragraphs look good. I especially like how concise they are

2022-03-07 20:56 UTC, merged