Correct unacceptable deadline information
burgess01/code-of-conduct pull request #13
Opened 2022-03-07 21:54 UTC by burgess01

## Correct unacceptable deadline information

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [ x] Documentation

## Contributors

- @burgess01

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-03-07 23:28 UTC, mariakimheinert requested changes
Hi @burgess01, thanks so much for making these changes. I've added a few suggestions. Please let me know if you have any questions!

2022-03-07 23:28 UTC, mariakimheinert commented on conduct.md
> +- Students who have a situation where they need an extension should contact the professor as soon as possible and should not wait until the last minute.
"as soon as possible" and "should not wait until the last minute" convey the same idea. Maybe it would be more concise to end at "as soon as possible"?

2022-03-07 23:28 UTC, mariakimheinert commented on conduct.md
> +- Students should not request an extension without serious and extenuating circumstances.
Perhaps instead of "without serious and extenuating circumstances", it might make more sense to write "unless they are facing a serious and extenuating circumstance"?

2022-03-08 00:14 UTC, laurennevill approved these changes
I think that after the professors suggestions are resolved that these are all good changes.

2022-03-08 00:31 UTC, burgess01 commented on conduct.md
> +- Students who have a situation where they need an extension should contact the professor as soon as possible and should not wait until the last minute.
Thats a lot better! I am fixing that right now.

2022-03-08 00:31 UTC, burgess01 commented on conduct.md
> +- Students should not request an extension without serious and extenuating circumstances.
I think that would make a lot more sense! I just corrected that point to say that instead.

2022-03-08 00:39 UTC, burgess01 commented
@mariakimheinert and @solisa986 I corrected the problems with my section. Is everything looking okay with the section now?

2022-03-08 00:46 UTC, mariakimheinert approved these changes
Looks great, @burgess01! Thanks again for updating this section of the conduct guide. :shipit:

2022-03-08 01:04 UTC, mariakimheinert approved these changes
:shipit:

2022-03-08 01:32 UTC, laurennevill approved these changes
Looks good. Great work Katie!

2022-03-08 01:33 UTC, merged

2022-03-08 01:38 UTC, solisa986 approved these changes
Looks good @burgess01 !