Acceptable deadlines Final Version PR
burgess01/code-of-conduct pull request #6
Opened 2022-03-01 21:19 UTC by tuduun

## Description

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-03-01 21:23 UTC, burgess01 approved these changes
I think these are good changes! I like how everything was written.

2022-03-01 21:25 UTC, laurennevill commented
I think these are pretty good. The only suggestion I might make is the wording of the second one. My only concern is that is if an emergency comes up, a student might not be able to contact a professor 24 hours in advance.

2022-03-01 21:27 UTC, MAbraham24 reviewed
These are some good changes, it sounds much more official!

2022-03-01 21:29 UTC, MAbraham24 approved these changes

2022-03-01 22:10 UTC, mariakimheinert requested changes
Hello @tuduun, thanks for your work on these changes! I've requested a couple of changes below. Additionally, would you please edit the initial comment so that all parts of the pull request template have been filled out?

2022-03-01 22:10 UTC, mariakimheinert commented on conduct.md
> +- Students should contact the professor if they have conflicts/emergencies and/or need extensions on their work 24 hours in advance.
This sentence should be reconsidered as the [course syllabus](https://mariakimheinert.com/software-engineering/course-syllabus/#assignment-submission) does not state any policy about notifying the instructor 24 hours in advance for an extension.

2022-03-01 22:10 UTC, mariakimheinert commented on conduct.md
> +- Students should be aware of deadlines and get assistance for assignments prior to end of deadlines.
An empty line should be inserted after this bullet point.

2022-03-02 18:34 UTC, solisa986 reviewed
once maria's changes are resolved, this should be good to merge. Great work!

2022-03-03 21:14 UTC, laurennevill approved these changes
Good work!

2022-03-04 17:51 UTC, mariakimheinert requested changes
Hi @tuduun, thanks for your work making the changes I requested previously! I added a comment below that needs further discussion. Additionally, it seems that you did not complete the pull request template in your initial comment--there is only a checkmark next to `Bug fix`, which is probably not the right classification for this PR. Would you please make sure to fill out all parts of the pull request template, including adding a description of these changes and listing yourself as a contributor?

2022-03-04 17:51 UTC, mariakimheinert commented on conduct.md
> +- Students should contact the professor and make special arrangements for their assignments if they have conflicts/emergencies.
I mentioned this in [another PR to another group](https://github.com/burgess01/code-of-conduct/pull/8#discussion_r819782704), but has there been class-wide discussion about whether I will be referred to as the "professor" or "instructor" in this document? It would be better to be consistent throughout the conduct guide.

2022-03-05 18:34 UTC, solisa986 approved these changes
This is good once Maria's change is addressed. Great work @tuduun!

2022-03-05 20:12 UTC, tuduun commented on conduct.md
> +- Students should contact the professor and make special arrangements for their assignments if they have conflicts/emergencies.
Yeah, I think we agreed on professor

2022-03-06 22:17 UTC, mariakimheinert approved these changes
@tuduun, thanks for your work on these changes! They look good to me.

2022-03-07 02:50 UTC, merged