Acceptable attendance
burgess01/code-of-conduct pull request #8
Opened 2022-03-01 21:20 UTC by MAbraham24

## Description

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-03-01 21:25 UTC, tuduun requested changes
You can edit the third bullet point's "to" to "for".

2022-03-01 21:30 UTC, laurennevill approved these changes
looks solid to me

2022-03-01 22:11 UTC, mariakimheinert commented on conduct.md
> +- Students should arrive to class on time and be ready to start class at 1040am.
The time should be reformatted to match the times stated in the [course syllabus](https://mariakimheinert.com/software-engineering/course-syllabus/#course-meeting-times). Additionally, do we want to add the time for the lab session as well?

2022-03-01 22:14 UTC, mariakimheinert commented on conduct.md
> +- Students should give prior notice if they are late to class, have conflicts with other classes, or are going to be absent before the class begins.
Could this statement include the detail from the "Course Attendance" section of the [course syllabus](https://mariakimheinert.com/software-engineering/course-syllabus/#course-attendance) about aiming to notify the instructor at least one week in advance of an absence?

2022-03-01 22:14 UTC, mariakimheinert commented on conduct.md
> +- Students should prepared for class.
Can this sentence be more specific about what "prepared" means?

2022-03-01 22:16 UTC, mariakimheinert commented on conduct.md
> +- Students who are late should check in with the professor and class mates in order to stay caught up with work.
Could it be clarified that the student should do this *after* the class session as to not cause further interruption?
Additionally, "class mates" should be "classmates".

2022-03-02 06:12 UTC, tuduun approved these changes

2022-03-02 18:32 UTC, solisa986 reviewed
once maria's review is resolved, this should be good

2022-03-03 21:13 UTC, laurennevill approved these changes
Looks great to me!

2022-03-04 17:46 UTC, mariakimheinert requested changes
Hi @MAbraham24, thanks for your hard work making the changes I requested previously. I have a few more suggestions below. Please let me know if you have any questions!

2022-03-04 17:46 UTC, mariakimheinert commented on conduct.md
> +Laboratory Session: Tuesday from 2:50 pm - 4:40 pm
Right now, these times will all appear on one line. Could they be made into bullet points that are indented below the "Students should arrive to..." bullet point above?

2022-03-04 17:46 UTC, mariakimheinert commented on conduct.md
> +- Students should give about one-week prior notice if they are late to class, have conflicts with other classes, or are going to be absent before the class begins.
Instead of "about one-week", this should be "at least one week".

2022-03-04 17:46 UTC, mariakimheinert commented on conduct.md
> +- Students should come to class prepared by completing labs, practicals, and reading discord to know any information needed for lessons.
Discord should be capitalized.

2022-03-04 17:46 UTC, mariakimheinert commented on conduct.md
> +- Students who are late should check in with the professor and classmates after class in order to stay caught up with work.
Has there been any discussion as a class about whether I will be addressed as the instructor or professor? I've seen both terms used and it would be better to be consistent throughout the entire conduct guide and only use one. @MAbraham24, if there hasn't been a discussion yet, could you open an issue in the [main Code of Conduct](https://github.com/cmpsc-203-s22/code-of-conduct/issues) repository so that people can discuss this there? And, it would be great if you could send a message in our course Discord channel to notify others that you've opened this issue.

2022-03-05 18:32 UTC, solisa986 requested changes
Great work @MAbraham24! I have requested some minor changes to your submission. If you have any questions about my changes, please feel free to leave a comment.

2022-03-05 18:32 UTC, solisa986 commented on conduct.md
> +- Students should arrive to class sessions, practical sessions and lab sessions on time. These times are:
there should be a comma after "practical sessions"

2022-03-05 18:32 UTC, solisa986 commented on conduct.md
> +- Students should give about one-week prior notice if they are late to class, have conflicts with other classes, or are going to be absent before the class begins.
since this is about prior notice, you should use "will be" when describing what they should give notice to. Ergo, "prior notice if they will be late to class" & "will be absent before the class begins".

2022-03-05 18:32 UTC, solisa986 commented on conduct.md
> +- Students should come to class prepared by completing labs, practicals, and reading discord to know any information needed for lessons.
there should be "completing" in front of "practicals".

2022-03-05 18:32 UTC, solisa986 commented on conduct.md
> +- Students who are late should check in with the professor and classmates after class in order to stay caught up with work.
there should be a "their" in front of "classmates".

2022-03-05 21:28 UTC, MAbraham24 commented
I resolved all of @solisa986 conflicts and I resolved all, but one of Professor @mariakimheinert conflicts. Please tell me if there is more change that you see fit to be made. I will resolve the final conflict tomorrow after getting confirmation from the class in addressing Professor Heinert's conflict.

2022-03-06 22:19 UTC, mariakimheinert requested changes
Hi @MAbraham24, I've requested one small change!

2022-03-06 22:19 UTC, mariakimheinert commented on conduct.md
> +- Laboratory Session: Tuesday from 2:50 pm - 4:40 pm
Each of these bullet points should be indented by two spaces.

2022-03-06 22:57 UTC, MAbraham24 commented
I indented the line by two spaces and got an error, so I instead left it at 1 space. Please look at it and tell me if it is satisfactory!

2022-03-07 01:16 UTC, mariakimheinert commented
> I indented the line by two spaces and got an error, so I instead left it at 1 space. Please look at it and tell me if it is satisfactory!

Hi @MAbraham24! Could you explain the error you saw when you indented by 2 spaces? The issue with indenting by only 1 space is that 1 space is not recognized in Markdown as a nested bullet item, so the items are still at the same level of indentation in the rendered Markdown.

2022-03-07 01:19 UTC, mariakimheinert commented
> > I indented the line by two spaces and got an error, so I instead left it at 1 space. Please look at it and tell me if it is satisfactory!
> 
> Hi @MAbraham24! Could you explain the error you saw when you indented by 2 spaces? The issue with indenting by only 1 space is that 1 space is not recognized in Markdown as a nested bullet item, so the items are still at the same level of indentation in the rendered Markdown.

Oh, @MAbraham24, I see what you did now. By indenting, I meant to place two spaces before each hyphen. So, 

```
- Students should arrive to class sessions, practical sessions, and lab sessions on time. These times are:

- Class Session: Monday and Wednesday from 10:40 am - 11:40 am

- Practical Session: Friday from 10:40 am - 11:40 am

- Laboratory Session: Tuesday from 2:50 pm - 4:40 pm

- Students should give at least one week prior notice if they will be late to class, have conflicts with other classes, or will be absent before the class begins.
```

should become

```
- Students should arrive to class sessions, practical sessions, and lab sessions on time. These times are:
  - Class Session: Monday and Wednesday from 10:40 am - 11:40 am
  - Practical Session: Friday from 10:40 am - 11:40 am
  - Laboratory Session: Tuesday from 2:50 pm - 4:40 pm
- Students should give at least one week prior notice if they will be late to class, have conflicts with other classes, or will be absent before the class begins.
```

2022-03-07 01:22 UTC, MAbraham24 commented
I got another error when I did that:
 Error: conduct.md:29:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2]
Error: conduct.md:31:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2]
Error: conduct.md:33:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2]
Error: Failed with exit code: 1

2022-03-07 01:24 UTC, mariakimheinert commented
> I got another error when I did that: Error: conduct.md:29:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2] Error: conduct.md:31:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2] Error: conduct.md:33:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 2] Error: Failed with exit code: 1

Can you push your changes?

2022-03-07 01:28 UTC, MAbraham24 commented
Alright, I pushed it.

2022-03-07 01:31 UTC, mariakimheinert commented
@MAbraham24, the spaces must go before each hyphen. That portion of the conduct should look exactly like the example I posted previously.

2022-03-07 01:35 UTC, MAbraham24 commented
Alright it's all good now

2022-03-07 16:23 UTC, mariakimheinert commented on conduct.md
> +
Although the Markdown linter is not complaining about it, [nested lists typically do not have empty lines before and after them](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#nested-lists). I recommend that the two empty lines around the nested list be removed.

2022-03-07 18:17 UTC, MAbraham24 commented
@mariakimheinert empty lines have been removed.

2022-03-07 18:46 UTC, solisa986 approved these changes
Looks good @MAbraham24! This is a really nice addition to your team's work.

2022-03-07 19:55 UTC, burgess01 approved these changes
I think this looks good!

2022-03-07 20:09 UTC, mariakimheinert approved these changes
Thanks for your hard work on these changes, @MAbraham24. They look good to me! :shipit:

2022-03-07 20:17 UTC, merged